services:
  postgres:
    image: postgres:16-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bankdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: ./etl
    container_name: bank_etl
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/data:ro
      - ./reports:/reports
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: bankdb
      DATA_FILE: /data/bank.csv

volumes:
  postgres_data:
